### PR TITLE
6-1-1.csv

### PR DESCRIPTION
**Pull request by johnkab**

### CODE REVIEW

**Comment by Norric1Admin** [comment]
Hi @johnkab, try selecting 'Resolve conflicts' above and deleting lines 1-3 and 5.

**Comment by johnkab** [comment]
@Norric1Admin <https://github.com/Norric1Admin> Thank, I have tried to update metadata of indicator_6-1-1 but the error is that, maping is not allowed.

**Comment by Norric1Admin** [comment]
No problem - if you send me the Pull Request link i can have a look. Usually, it means there is a ':' somewhere in the value (it should give you the line number too). Replace the colon with a dash.

**Comment by johnkab** [comment]
It’s done. Thank you.

**Pull request closed without merging**
